### ISSUE TITLE
Requirements for the Initial Release

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-vscode-extensions#4]
- [ ] Descriptions for New Project Page https://github.com/telerik/kendo-react-scrolls/issues/21
- [ ] Descriptions for the Select Framework Page  https://github.com/telerik/kendo-react-scrolls/issues/21 
- [ ] Template for Angular should be rewritten to match the one for React https://github.com/telerik/k2/issues/162
- [ ] Define App Drawer Usage in the Generated App
